// Auto-generated by scripts/generateTokenData.js — do not edit directly.
export const tokenData = {
  "base": {
    "color": {
      "color": {
        "lorax": {
          "default": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                1,
                0.4784,
                0.349
              ],
              "alpha": 1,
              "hex": "#ff7a59"
            },
            "$type": "color",
            "$description": "rgb(255, 122, 89)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:3"
              }
            }
          },
          "dark": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.902,
                0.4314,
                0.3137
              ],
              "alpha": 1,
              "hex": "#e66e50"
            },
            "$type": "color",
            "$description": "rgb(230, 110, 80)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:4"
              }
            }
          },
          "medium": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                1,
                0.7373,
                0.6745
              ],
              "alpha": 1,
              "hex": "#ffbcac"
            },
            "$type": "color",
            "$description": "rgb(255, 188, 172)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:5"
              }
            }
          },
          "light": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                1,
                0.9451,
                0.9333
              ],
              "alpha": 1,
              "hex": "#fff1ee"
            },
            "$type": "color",
            "$description": "rgb(255, 241, 238)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:6"
              }
            }
          }
        },
        "calypso": {
          "default": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0,
                0.6431,
                0.7412
              ],
              "alpha": 1,
              "hex": "#00a4bd"
            },
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:7"
              }
            }
          },
          "dark": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0,
                0.5686,
                0.6824
              ],
              "alpha": 1,
              "hex": "#0091ae"
            },
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:8"
              }
            }
          },
          "medium": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.498,
                0.8196,
                0.8706
              ],
              "alpha": 1,
              "hex": "#7fd1de"
            },
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:9"
              }
            }
          },
          "light": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.898,
                0.9608,
                0.9725
              ],
              "alpha": 1,
              "hex": "#e5f5f8"
            },
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:10"
              }
            }
          }
        },
        "candy apple": {
          "default": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.949,
                0.3294,
                0.3569
              ],
              "alpha": 1,
              "hex": "#f2545b"
            },
            "$type": "color",
            "$description": "rgb(242, 84, 91)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:11"
              }
            }
          },
          "dark": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.851,
                0.298,
                0.3255
              ],
              "alpha": 1,
              "hex": "#d94c53"
            },
            "$type": "color",
            "$description": "rgb(217, 76, 83)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:12"
              }
            }
          },
          "medium": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9725,
                0.6627,
                0.6784
              ],
              "alpha": 1,
              "hex": "#f8a9ad"
            },
            "$type": "color",
            "$description": "rgb(248, 169, 173)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:13"
              }
            }
          },
          "light": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9922,
                0.9294,
                0.9333
              ],
              "alpha": 1,
              "hex": "#fdedee"
            },
            "$type": "color",
            "$description": "rgb(253, 237, 238)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:14"
              }
            }
          }
        },
        "marigold": {
          "default": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9608,
                0.7608,
                0.4196
              ],
              "alpha": 1,
              "hex": "#f5c26b"
            },
            "$type": "color",
            "$description": "rgb(245, 194, 107)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:15"
              }
            }
          },
          "dark": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.8588,
                0.6824,
                0.3765
              ],
              "alpha": 1,
              "hex": "#dbae60"
            },
            "$type": "color",
            "$description": "rgb(219, 174, 96)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:16"
              }
            }
          },
          "medium": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9804,
                0.8784,
                0.7098
              ],
              "alpha": 1,
              "hex": "#fae0b5"
            },
            "$type": "color",
            "$description": "rgb(250, 224, 181)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:17"
              }
            }
          },
          "light": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9961,
                0.9725,
                0.9412
              ],
              "alpha": 1,
              "hex": "#fef8f0"
            },
            "$type": "color",
            "$description": "rgb(254, 248, 240)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:18"
              }
            }
          }
        },
        "oz": {
          "default": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0,
                0.7412,
                0.6471
              ],
              "alpha": 1,
              "hex": "#00bda5"
            },
            "$type": "color",
            "$description": "rgb(0, 189, 165)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:19"
              }
            }
          },
          "dark": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0,
                0.6392,
                0.5529
              ],
              "alpha": 1,
              "hex": "#00a38d"
            },
            "$type": "color",
            "$description": "rgb(0, 163, 141)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:20"
              }
            }
          },
          "medium": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.498,
                0.8706,
                0.8235
              ],
              "alpha": 1,
              "hex": "#7fded2"
            },
            "$type": "color",
            "$description": "rgb(127, 222, 210)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:21"
              }
            }
          },
          "light": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.898,
                0.9725,
                0.9647
              ],
              "alpha": 1,
              "hex": "#e5f8f6"
            },
            "$type": "color",
            "$description": "rgb(229, 248, 246)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:22"
              }
            }
          }
        },
        "norman": {
          "default": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.949,
                0.3294,
                0.4902
              ],
              "alpha": 1,
              "hex": "#f2547d"
            },
            "$type": "color",
            "$description": "rgb(242, 84, 125)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:23"
              }
            }
          },
          "dark": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.851,
                0.298,
                0.4431
              ],
              "alpha": 1,
              "hex": "#d94c71"
            },
            "$type": "color",
            "$description": "rgb(217, 76, 113)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:24"
              }
            }
          },
          "medium": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9765,
                0.6667,
                0.7451
              ],
              "alpha": 1,
              "hex": "#f9aabe"
            },
            "$type": "color",
            "$description": "rgb(249, 170, 190)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:25"
              }
            }
          },
          "light": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9922,
                0.9294,
                0.949
              ],
              "alpha": 1,
              "hex": "#fdedf2"
            },
            "$type": "color",
            "$description": "rgb(253, 237, 242)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:26"
              }
            }
          }
        },
        "sorbet": {
          "default": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                1,
                0.5608,
                0.349
              ],
              "alpha": 1,
              "hex": "#ff8f59"
            },
            "$type": "color",
            "$description": "rgb(255, 143, 89)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:27"
              }
            }
          },
          "dark": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.902,
                0.5098,
                0.3137
              ],
              "alpha": 1,
              "hex": "#e68250"
            },
            "$type": "color",
            "$description": "rgb(230, 130, 80)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:28"
              }
            }
          },
          "medium": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                1,
                0.7804,
                0.6745
              ],
              "alpha": 1,
              "hex": "#ffc7ac"
            },
            "$type": "color",
            "$description": "rgb(255, 199, 172)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:29"
              }
            }
          },
          "light": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                1,
                0.9529,
                0.9333
              ],
              "alpha": 1,
              "hex": "#fff3ee"
            },
            "$type": "color",
            "$description": "rgb(255, 243, 238)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:30"
              }
            }
          }
        },
        "thunderdome": {
          "default": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.4157,
                0.4706,
                0.8196
              ],
              "alpha": 1,
              "hex": "#6a78d1"
            },
            "$type": "color",
            "$description": "rgb(106, 120, 209)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:31"
              }
            }
          },
          "dark": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.3686,
                0.4157,
                0.7216
              ],
              "alpha": 1,
              "hex": "#5e6ab8"
            },
            "$type": "color",
            "$description": "rgb(94, 106, 184)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:32"
              }
            }
          },
          "medium": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.7059,
                0.7333,
                0.9098
              ],
              "alpha": 1,
              "hex": "#b4bbe8"
            },
            "$type": "color",
            "$description": "rgb(180, 187, 232)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:33"
              }
            }
          },
          "light": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9412,
                0.9451,
                0.9804
              ],
              "alpha": 1,
              "hex": "#f0f1fa"
            },
            "$type": "color",
            "$description": "rgb(240, 241, 250)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:34"
              }
            }
          }
        },
        "neutral": {
          "flat earth": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.1451,
                0.2,
                0.2588
              ],
              "alpha": 1,
              "hex": "#253342"
            },
            "$type": "color",
            "$description": "rgb(37, 51, 66)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:35"
              }
            }
          },
          "pantera": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.1765,
                0.2431,
                0.3137
              ],
              "alpha": 1,
              "hex": "#2d3e50"
            },
            "$type": "color",
            "$description": "rgb(45, 62, 80)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:36"
              }
            }
          },
          "heffalump": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.2588,
                0.3569,
                0.4627
              ],
              "alpha": 1,
              "hex": "#425b76"
            },
            "$type": "color",
            "$description": "rgb(66, 91, 118)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:37"
              }
            }
          },
          "slinky": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.3176,
                0.4353,
                0.5647
              ],
              "alpha": 1,
              "hex": "#516f90"
            },
            "$type": "color",
            "$description": "rgb(81, 111, 144)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:38"
              }
            }
          },
          "eerie": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.4863,
                0.5961,
                0.7137
              ],
              "alpha": 1,
              "hex": "#7c98b6"
            },
            "$type": "color",
            "$description": "rgb(124, 152, 182)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:39"
              }
            }
          },
          "flint": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.6,
                0.6745,
                0.7608
              ],
              "alpha": 1,
              "hex": "#99acc2"
            },
            "$type": "color",
            "$description": "rgb(153, 172, 194)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:40"
              }
            }
          },
          "battleship": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.7961,
                0.8392,
                0.8863
              ],
              "alpha": 1,
              "hex": "#cbd6e2"
            },
            "$type": "color",
            "$description": "rgb(203, 214, 226)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:41"
              }
            }
          },
          "great white": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.8745,
                0.8902,
                0.9216
              ],
              "alpha": 1,
              "hex": "#dfe3eb"
            },
            "$type": "color",
            "$description": "rgb(223, 227, 235)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:42"
              }
            }
          },
          "koala": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9176,
                0.9412,
                0.9647
              ],
              "alpha": 1,
              "hex": "#eaf0f6"
            },
            "$type": "color",
            "$description": "rgb(234, 240, 246)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:43"
              }
            }
          },
          "gypsum": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.9608,
                0.9725,
                0.9804
              ],
              "alpha": 1,
              "hex": "#f5f8fa"
            },
            "$type": "color",
            "$description": "rgb(245, 248, 250)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:44"
              }
            }
          },
          "olaf": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                1,
                1,
                1
              ],
              "alpha": 1,
              "hex": "#ffffff"
            },
            "$type": "color",
            "$description": "rgb(255, 255, 255)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:45"
              }
            }
          },
          "monolith": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0,
                0,
                0
              ],
              "alpha": 1,
              "hex": "#000000"
            },
            "$type": "color",
            "$description": "rgb(0, 0, 0)",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:46"
              }
            }
          }
        },
        "obsidian": {
          "$value": {
            "colorSpace": "srgb",
            "components": [
              0.8824,
              0.2,
              0.2
            ],
            "alpha": 1,
            "hex": "#e13333"
          },
          "$type": "color",
          "$description": "rgb(51, 71, 91)",
          "$extensions": {
            "com.figma": {
              "variableId": "VariableID:15:47"
            }
          }
        }
      }
    },
    "space": {
      "space": {
        "0": {
          "$value": "0",
          "$type": "spacing"
        },
        "2": {
          "$value": "2px",
          "$type": "spacing"
        },
        "4": {
          "$value": "4px",
          "$type": "spacing"
        },
        "6": {
          "$value": "6px",
          "$type": "spacing"
        },
        "8": {
          "$value": "8px",
          "$type": "spacing"
        },
        "10": {
          "$value": "10px",
          "$type": "spacing"
        },
        "12": {
          "$value": "12px",
          "$type": "spacing"
        },
        "14": {
          "$value": "14px",
          "$type": "spacing"
        },
        "16": {
          "$value": "16px",
          "$type": "spacing"
        },
        "18": {
          "$value": "18px",
          "$type": "spacing"
        },
        "20": {
          "$value": "20px",
          "$type": "spacing"
        },
        "24": {
          "$value": "24px",
          "$type": "spacing"
        },
        "28": {
          "$value": "28px",
          "$type": "spacing"
        },
        "32": {
          "$value": "32px",
          "$type": "spacing"
        },
        "36": {
          "$value": "36px",
          "$type": "spacing"
        },
        "40": {
          "$value": "40px",
          "$type": "spacing"
        },
        "44": {
          "$value": "44px",
          "$type": "spacing"
        },
        "48": {
          "$value": "48px",
          "$type": "spacing"
        },
        "52": {
          "$value": "52px",
          "$type": "spacing"
        },
        "56": {
          "$value": "56px",
          "$type": "spacing"
        },
        "60": {
          "$value": "60px",
          "$type": "spacing"
        }
      }
    },
    "border": {
      "radius": {
        "border": {
          "0": {
            "$value": "0",
            "$type": "borderRadius",
            "$description": "No border radius"
          },
          "3": {
            "$value": "3px",
            "$type": "borderRadius",
            "$description": "Border radius of most elements in product"
          },
          "6": {
            "$value": "6px",
            "$type": "borderRadius",
            "$description": "Border radius of less rounded sides of a ribbon"
          },
          "20": {
            "$value": "20px",
            "$type": "borderRadius",
            "$description": "Radius of more rounded side of a ribbon"
          },
          "24": {
            "$value": "24px",
            "$type": "borderRadius",
            "$description": "Border radius of an active indicator in Tabs"
          },
          "500": {
            "$value": "500px",
            "$type": "borderRadius",
            "$description": "Radius of notification badge (This pixel based token could likely be combined with the 50% and 100% tokens). They all accomplish the same effect. This would need more test to confirm."
          },
          "50percent": {
            "$value": "50%",
            "$type": "borderRadius",
            "$description": "Radius of rounded, circular elements."
          }
        }
      },
      "width": {
        "border": {
          "0": {
            "$value": "0",
            "$type": "borderWidth",
            "$description": "No border"
          },
          "1": {
            "$value": "1px",
            "$type": "borderWidth",
            "$description": "Most borders in the product"
          },
          "2": {
            "$value": "2px",
            "$type": "borderWidth",
            "$description": "Checkbox border width"
          }
        }
      }
    },
    "fontFamily": {
      "fontFamily": {
        "code": {
          "$value": "Source Code Pro, Consolas, Monaco, Courier New, monospace",
          "$type": "fontFamilies",
          "$description": "Font used for code"
        },
        "default": {
          "$value": "Lexend Deca, Helvetica, Arial, sans-serif",
          "$type": "fontFamilies",
          "$description": "The default font family for the product"
        },
        "body": {
          "fallback": {
            "$value": "Helvetica, Arial, sans-serif",
            "$type": "fontFamilies",
            "$description": "The default fallback stack for body copy in product."
          }
        },
        "monospace": {
          "fallback": {
            "$value": "Consolas, Monaco, Courier New, monospace",
            "$type": "fontFamilies",
            "$description": "The fallback stack for code font"
          }
        }
      }
    },
    "fontSize": {
      "fontSize": {
        "12": {
          "$value": "12px",
          "$type": "fontSizes",
          "$description": "Primarily used for microcopy."
        },
        "14": {
          "$value": "14px",
          "$type": "fontSizes",
          "$description": "Default size of body copy in product. Used across the vast majority of components."
        },
        "16": {
          "$value": "16px",
          "$type": "fontSizes",
          "$description": "Used in Forms and H5."
        },
        "20": {
          "$value": "20px",
          "$type": "fontSizes",
          "$description": "Used for H4 and Page Header components"
        },
        "22": {
          "$value": "22px",
          "$type": "fontSizes",
          "$description": "Used in H3"
        },
        "24": {
          "$value": "24px",
          "$type": "fontSizes",
          "$description": "Used in H2"
        },
        "32": {
          "$value": "32px",
          "$type": "fontSizes",
          "$description": "Used in H1."
        },
        "55": {
          "$value": "55px",
          "$type": "fontSizes",
          "$description": "Used in Tagline Heading."
        }
      }
    },
    "fontWeight": {
      "fontWeight": {
        "300": {
          "$value": "300",
          "$type": "fontWeights",
          "$description": "300 = Light."
        },
        "500": {
          "$value": "500",
          "$type": "fontWeights",
          "$description": "500 = Medium"
        },
        "600": {
          "$value": "600",
          "$type": "fontWeights",
          "$description": "600 = Semi Bold (Demibold)"
        },
        "700": {
          "$value": "700",
          "$type": "fontWeights",
          "$description": "700 = Bold"
        }
      }
    },
    "lineHeight": {
      "lineHeight": {
        "18": {
          "$value": "18px",
          "$type": "lineHeights",
          "$description": "Used for Microcopy"
        },
        "22": {
          "$value": "22px",
          "$type": "lineHeights",
          "$description": "Line height of text within an Input"
        },
        "24": {
          "$value": "24px",
          "$type": "lineHeights",
          "$description": "Used for body copy. The default, universal line-height for text in the App."
        },
        "normal": {
          "$value": "1.2",
          "$type": "lineHeights",
          "$description": "Widely used CSS rule throughout our components. Typically unitless line height equals 1.2 of the size it is applied to."
        },
        "oneFour": {
          "$value": "1.4",
          "$type": "lineHeights",
          "$description": "Unitless lineheight used for text in Alerts"
        }
      }
    },
    "iconSize": {
      "iconSize": {
        "8": {
          "$value": "8px",
          "$type": "dimension"
        },
        "12": {
          "$value": "12px",
          "$type": "dimension"
        },
        "14": {
          "$value": "14px",
          "$type": "dimension"
        },
        "16": {
          "$value": "16px",
          "$type": "dimension"
        },
        "18": {
          "$value": "18px",
          "$type": "dimension"
        },
        "20": {
          "$value": "20px",
          "$type": "dimension"
        },
        "24": {
          "$value": "24px",
          "$type": "dimension"
        },
        "28": {
          "$value": "28px",
          "$type": "dimension"
        },
        "32": {
          "$value": "32px",
          "$type": "dimension"
        },
        "36": {
          "$value": "36px",
          "$type": "dimension"
        }
      }
    },
    "motion": {
      "timing": {
        "duration": {
          "100": {
            "$value": "100ms",
            "$type": "duration"
          },
          "150": {
            "$value": "150ms",
            "$type": "duration"
          },
          "200": {
            "$value": "200ms",
            "$type": "duration"
          },
          "250": {
            "$value": "250ms",
            "$type": "duration"
          },
          "300": {
            "$value": "300ms",
            "$type": "duration"
          },
          "350": {
            "$value": "350ms",
            "$type": "duration"
          }
        },
        "function": {
          "ease": {
            "$value": [
              {},
              {},
              {},
              {}
            ],
            "$type": "cubicBezier"
          },
          "linear": {
            "$value": [
              {},
              {},
              {},
              {}
            ],
            "$type": "cubicBezier"
          },
          "easeIn": {
            "$value": [
              {},
              {},
              {},
              {}
            ],
            "$type": "cubicBezier"
          },
          "easeOut": {
            "$value": [
              {},
              {},
              {},
              {}
            ],
            "$type": "cubicBezier"
          },
          "easeInOut": {
            "$value": [
              {},
              {},
              {},
              {}
            ],
            "$type": "cubicBezier"
          }
        }
      }
    },
    "textTransform": {
      "textTransform": {
        "none": {
          "$value": "none",
          "$type": "textCase",
          "$description": "Text will render as typed"
        },
        "uppercase": {
          "$value": "uppercase",
          "$type": "textCase",
          "$description": "Token will transform the text to UPPERCASE, regardless of the capitialization specified while the user typed"
        }
      }
    }
  },
  "semantic": {
    "color": {
      "color": {
        "text": {
          "default": {
            "$value": "{color.obsidian}",
            "$type": "color",
            "$description": "The default color of text in the product.",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:49"
              }
            }
          },
          "subtle": {
            "$value": "{color.neutral.flat earth}",
            "$type": "color",
            "$description": "The color of microcopy in the product",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:50"
              }
            }
          },
          "nonessential": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.4863,
                0.5961,
                0.7137
              ],
              "alpha": 1,
              "hex": "#7c98b6"
            },
            "$type": "color",
            "$description": "The color of placeholder text inside an input",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:51"
              }
            }
          },
          "disabled": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0.6902,
                0.7569,
                0.8314
              ],
              "alpha": 1,
              "hex": "#b0c1d4"
            },
            "$type": "color",
            "$description": "The color text within a disabled interactive element",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:52"
              }
            }
          },
          "inverse": {
            "$value": "{color.neutral.olaf}",
            "$type": "color",
            "$description": "The color of text when placed on a dark background",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:53"
              }
            }
          },
          "danger": {
            "$value": "{color.candy apple.default}",
            "$type": "color",
            "$description": "The color of microcopy that indicates an error or danger message",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:54"
              }
            }
          },
          "success": {
            "$value": "{color.oz.dark}",
            "$type": "color",
            "$description": "The color of microcopy that indicates success or positive messaging",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:55"
              }
            }
          }
        },
        "surface": {
          "default": {
            "$value": "{color.neutral.olaf}",
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:56"
              }
            }
          },
          "elevation1": {
            "$value": "{color.neutral.gypsum}",
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:57"
              }
            }
          },
          "transparent": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0,
                0,
                0
              ],
              "alpha": 0,
              "hex": "#000000"
            },
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:58"
              }
            }
          }
        }
      }
    },
    "colorDark": {
      "color": {
        "text": {
          "default": {
            "$value": "{color.neutral.gypsum}",
            "$type": "color",
            "$description": "The default color of text in the product.",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:49"
              }
            }
          },
          "subtle": {
            "$value": "{color.neutral.koala}",
            "$type": "color",
            "$description": "The color of microcopy in the product",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:50"
              }
            }
          },
          "nonessential": {
            "$value": "{color.neutral.battleship}",
            "$type": "color",
            "$description": "The color of placeholder text inside an input",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:51"
              }
            }
          },
          "disabled": {
            "$value": "{color.neutral.flint}",
            "$type": "color",
            "$description": "The color text within a disabled interactive element",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:52"
              }
            }
          },
          "inverse": {
            "$value": "{color.neutral.monolith}",
            "$type": "color",
            "$description": "The color of text when placed on a dark background",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:53"
              }
            }
          },
          "danger": {
            "$value": "{color.candy apple.medium}",
            "$type": "color",
            "$description": "The color of microcopy that indicates an error or danger message",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:54"
              }
            }
          },
          "success": {
            "$value": "{color.oz.medium}",
            "$type": "color",
            "$description": "The color of microcopy that indicates success or positive messaging",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:55"
              }
            }
          }
        },
        "surface": {
          "default": {
            "$value": "{color.neutral.flat earth}",
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:56"
              }
            }
          },
          "elevation1": {
            "$value": "{color.neutral.heffalump}",
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:57"
              }
            }
          },
          "transparent": {
            "$value": {
              "colorSpace": "srgb",
              "components": [
                0,
                0,
                0
              ],
              "alpha": 0,
              "hex": "#000000"
            },
            "$type": "color",
            "$extensions": {
              "com.figma": {
                "variableId": "VariableID:15:58"
              }
            }
          }
        }
      }
    },
    "typography": {
      "text": {
        "body": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "fontWeight": "{fontWeight.body.default}",
            "lineHeight": "{lineHeight.body.default}",
            "fontSize": "{typeScale.body.default}"
          },
          "$type": "typography",
          "$description": "Default body copy. Composite token."
        },
        "bodyLarge": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "fontWeight": "{fontWeight.body.default}",
            "lineHeight": "{lineHeight.body.default}",
            "fontSize": "{typeScale.body.large}"
          },
          "$type": "typography",
          "$description": "Large body copy. Composite token."
        },
        "bodySmall": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "fontWeight": "{fontWeight.body.default}",
            "lineHeight": "{lineHeight.body.tight}",
            "fontSize": "{typeScale.body.small}"
          },
          "$type": "typography"
        },
        "code": {
          "$value": {
            "fontFamily": "{fontFamily.code}",
            "fontWeight": "{fontWeight.code.default}",
            "fontSize": "{typeScale.body.default}",
            "lineHeight": "{lineHeight.body.default}"
          },
          "$type": "typography"
        }
      },
      "display": {
        "heading1": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "fontWeight": "{fontWeight.display.bold}",
            "lineHeight": "{typeScale.display.heading1} * {lineHeight.display}",
            "fontSize": "{typeScale.display.heading1}"
          },
          "$type": "typography"
        },
        "heading2": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "lineHeight": "{typeScale.display.heading2} * {lineHeight.display}",
            "fontSize": "{typeScale.display.heading2}",
            "fontWeight": "{fontWeight.display.light}"
          },
          "$type": "typography"
        },
        "heading3": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "fontWeight": "{fontWeight.display.medium}",
            "lineHeight": "{typeScale.display.heading3} * {lineHeight.display}",
            "fontSize": "{typeScale.display.heading3}"
          },
          "$type": "typography"
        },
        "heading4": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "lineHeight": "{typeScale.display.heading4} * {lineHeight.display}",
            "fontSize": "{typeScale.display.heading4}",
            "fontWeight": "{fontWeight.display.default}"
          },
          "$type": "typography"
        },
        "heading5": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "lineHeight": "{typeScale.display.heading5} * {lineHeight.display}",
            "fontSize": "{typeScale.display.heading5}",
            "fontWeight": "{fontWeight.display.default}"
          },
          "$type": "typography"
        },
        "heading6": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "lineHeight": "{typeScale.display.heading6} * {lineHeight.display}",
            "fontSize": "{typeScale.display.heading6}",
            "fontWeight": "{fontWeight.display.default}"
          },
          "$type": "typography"
        },
        "tagline": {
          "$value": {
            "fontFamily": "{fontFamily.default}",
            "fontWeight": "{fontWeight.display.bold}",
            "fontSize": "{fontSize.55}",
            "lineHeight": "{fontSize.55} * {lineHeight.display}"
          },
          "$type": "typography"
        },
        "pageHeading": {
          "$value": {
            "fontSize": "{typeScale.display.heading4}",
            "lineHeight": "{typeScale.display.heading4} * {lineHeight.display}",
            "fontWeight": "{fontWeight.display.default}",
            "fontFamily": "{fontFamily.default}"
          },
          "$type": "typography",
          "$description": "Page Heading"
        }
      }
    },
    "typeScale": {
      "typeScale": {
        "body": {
          "default": {
            "$value": "{typeScale.body.medium}",
            "$type": "fontSizes",
            "$description": "Default size of body copy"
          },
          "small": {
            "$value": "{fontSize.12}",
            "$type": "fontSizes",
            "$description": "The size of microcopy"
          },
          "medium": {
            "$value": "{fontSize.14}",
            "$type": "fontSizes"
          },
          "large": {
            "$value": "{fontSize.16}",
            "$type": "fontSizes",
            "$description": "The size of text within an input"
          }
        },
        "display": {
          "heading1": {
            "$value": "{fontSize.32}",
            "$type": "fontSizes"
          },
          "heading2": {
            "$value": "{fontSize.24}",
            "$type": "fontSizes"
          },
          "heading3": {
            "$value": "{fontSize.22}",
            "$type": "fontSizes"
          },
          "heading4": {
            "$value": "{fontSize.20}",
            "$type": "fontSizes"
          },
          "heading5": {
            "$value": "{fontSize.16}",
            "$type": "fontSizes"
          },
          "heading6": {
            "$value": "{fontSize.14}",
            "$type": "fontSizes"
          }
        },
        "code": {
          "default": {
            "$value": "{typeScale.body.default}",
            "$type": "fontSizes",
            "$description": "The default size of code text"
          }
        }
      }
    },
    "space": {
      "space": {
        "50": {
          "$value": "{space.2}",
          "$type": "spacing"
        },
        "100": {
          "$value": "{space.4}",
          "$type": "spacing"
        },
        "150": {
          "$value": "{space.6}",
          "$type": "spacing"
        },
        "200": {
          "$value": "{space.8}",
          "$type": "spacing"
        },
        "250": {
          "$value": "{space.10}",
          "$type": "spacing"
        },
        "300": {
          "$value": "{space.12}",
          "$type": "spacing"
        },
        "350": {
          "$value": "{space.14}",
          "$type": "spacing"
        },
        "400": {
          "$value": "{space.16}",
          "$type": "spacing"
        },
        "450": {
          "$value": "{space.18}",
          "$type": "spacing"
        },
        "500": {
          "$value": "{space.20}",
          "$type": "spacing"
        },
        "600": {
          "$value": "{space.24}",
          "$type": "spacing"
        },
        "700": {
          "$value": "{space.28}",
          "$type": "spacing"
        },
        "800": {
          "$value": "{space.32}",
          "$type": "spacing"
        },
        "900": {
          "$value": "{space.36}",
          "$type": "spacing"
        },
        "1000": {
          "$value": "{space.40}",
          "$type": "spacing"
        },
        "1100": {
          "$value": "{space.44}",
          "$type": "spacing"
        },
        "1200": {
          "$value": "{space.48}",
          "$type": "spacing"
        },
        "1300": {
          "$value": "{space.52}",
          "$type": "spacing"
        },
        "1400": {
          "$value": "{space.56}",
          "$type": "spacing"
        },
        "1500": {
          "$value": "{space.60}",
          "$type": "spacing"
        },
        "none": {
          "$value": "{space.0}",
          "$type": "spacing"
        }
      }
    },
    "border": {
      "color": {
        "border": {
          "default": {
            "$value": "{color.neutral.battleship}",
            "$type": "color",
            "$description": "Most common border color"
          },
          "subtle": {
            "$value": "{color.neutral.great white}",
            "$type": "color",
            "$description": "Border color for Tiles, MultiColumns, Tables"
          },
          "table": {
            "$value": "{color.neutral.great white}",
            "$type": "color",
            "$description": "Deprecated in favor of subtle token"
          },
          "selectable": {
            "$value": "{color.calypso.medium}",
            "$type": "color",
            "$description": "Border color of selectable buttons"
          },
          "dropzone": {
            "idle": {
              "$value": "{color.neutral.slinky}",
              "$type": "color",
              "$description": "Default border color of a drop zone"
            },
            "hover": {
              "$value": "{color.calypso.default}",
              "$type": "color",
              "$description": "Hover border color of a drop zone"
            },
            "procession": {
              "$value": "{color.neutral.gypsum}",
              "$type": "color",
              "$description": "Processing border color of a drop zone"
            },
            "error": {
              "$value": "{color.candy apple.dark}",
              "$type": "color",
              "$description": "Error border color of a drop zone"
            }
          },
          "active": {
            "$value": "#00d0e480",
            "$type": "color",
            "$description": "Border color of input elements in active state"
          }
        }
      },
      "radius": {
        "border": {
          "none": {
            "$value": "{radius.border.0}",
            "$type": "borderRadius"
          },
          "default": {
            "$value": "{radius.border.3}",
            "$type": "borderRadius",
            "$description": "Default border radius"
          },
          "circle": {
            "$value": "{radius.border.50percent}",
            "$type": "borderRadius"
          }
        }
      },
      "width": {
        "border": {
          "none": {
            "$value": "{width.border.0}",
            "$type": "borderWidth"
          },
          "default": {
            "$value": "{width.border.1}",
            "$type": "borderWidth"
          }
        }
      },
      "border": {
        "default": {
          "$value": {
            "color": "{color.border.default}",
            "width": "{width.border.default}",
            "style": "solid"
          },
          "$type": "border",
          "$description": "Composite token for most container borders"
        },
        "subtle": {
          "$value": {
            "color": "{color.border.subtle}",
            "width": "{width.border.default}",
            "style": "solid"
          },
          "$type": "border",
          "$description": "Composite border token for Tiles, Multicolumns, Tables"
        }
      }
    },
    "fontWeight": {
      "fontWeight": {
        "body": {
          "default": {
            "$value": "{fontWeight.300}",
            "$type": "fontWeights"
          },
          "bold": {
            "$value": "{fontWeight.600}",
            "$type": "fontWeights"
          }
        },
        "display": {
          "light": {
            "$value": "{fontWeight.300}",
            "$type": "fontWeights",
            "$description": "Font weight of H2 variant"
          },
          "medium": {
            "$value": "{fontWeight.500}",
            "$type": "fontWeights",
            "$description": "Font weight of H3 variant\n"
          },
          "default": {
            "$value": "{fontWeight.600}",
            "$type": "fontWeights",
            "$description": "Font weight of PageHeading, H4, H5, H6, H7 variants."
          },
          "bold": {
            "$value": "{fontWeight.700}",
            "$type": "fontWeights",
            "$description": "Font weight of H1 variant"
          }
        },
        "code": {
          "default": {
            "$value": "{fontWeight.500}",
            "$type": "fontWeights"
          }
        }
      }
    },
    "lineHeight": {
      "lineHeight": {
        "body": {
          "default": {
            "$value": "{lineHeight.24}",
            "$type": "lineHeights",
            "$description": "The default line height for body copy across the product."
          },
          "tight": {
            "$value": "{lineHeight.18}",
            "$type": "lineHeights"
          }
        },
        "display": {
          "$value": "{lineHeight.normal}",
          "$type": "lineHeights",
          "$description": "All headlines of our type scale are set to normal aka 1.2 (unitless)"
        },
        "code": {
          "$value": "{lineHeight.body.default}",
          "$type": "lineHeights"
        }
      }
    },
    "iconSize": {
      "iconSize": {
        "300": {
          "$value": "{iconSize.12}",
          "$type": "dimension"
        },
        "350": {
          "$value": "{iconSize.14}",
          "$type": "dimension"
        },
        "400": {
          "$value": "{iconSize.16}",
          "$type": "dimension"
        },
        "450": {
          "$value": "{iconSize.18}",
          "$type": "dimension"
        },
        "500": {
          "$value": "{iconSize.20}",
          "$type": "dimension"
        },
        "600": {
          "$value": "{iconSize.24}",
          "$type": "dimension"
        },
        "700": {
          "$value": "{iconSize.28}",
          "$type": "dimension"
        },
        "800": {
          "$value": "{iconSize.32}",
          "$type": "dimension"
        }
      }
    },
    "motion": {
      "disclosure": {
        "duration": {
          "maxHeight": {
            "default": {
              "$value": "{timing.duration.200}",
              "$type": "duration"
            }
          },
          "opacity": {
            "default": {
              "$value": "{timing.duration.200}",
              "$type": "duration"
            }
          },
          "transform": {
            "default": {
              "$value": "{timing.duration.200}",
              "$type": "duration"
            }
          }
        },
        "easing": {
          "maxHeight": {
            "default": {
              "$value": "{timing.function.ease}",
              "$type": "cubicBezier"
            }
          },
          "opacity": {
            "default": {
              "$value": "{timing.function.easeInOut}",
              "$type": "cubicBezier"
            }
          },
          "transform": {
            "default": {
              "$value": "{timing.function.easeInOut}",
              "$type": "cubicBezier"
            }
          }
        }
      }
    }
  }
};
