/**
 * Reads all design token JSON files and writes a single JS module
 * that Storybook/Vite can import without needing JSON plugin support.
 * Run: node scripts/generateTokenData.js
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

function readJson(relPath) {
  return JSON.parse(readFileSync(resolve(root, relPath), 'utf8'));
}

const data = {
  base: {
    color: readJson('figma-tokens/Base/color.json'),
    space: readJson('figma-tokens/Base/space.json'),
    border: readJson('figma-tokens/Base/border.json'),
    fontFamily: readJson('figma-tokens/Base/fontFamily.json'),
    fontSize: readJson('figma-tokens/Base/fontSize.json'),
    fontWeight: readJson('figma-tokens/Base/fontWeight.json'),
    lineHeight: readJson('figma-tokens/Base/lineHeight.json'),
    iconSize: readJson('figma-tokens/Base/iconSize.json'),
    motion: readJson('figma-tokens/Base/motion.json'),
    textTransform: readJson('figma-tokens/Base/textTransform.json'),
  },
  semantic: {
    color: readJson('figma-tokens/Semantic/color.json'),
    colorDark: readJson('figma-tokens/Semantic/color-dark.json'),
    typography: readJson('figma-tokens/Semantic/typography.json'),
    typeScale: readJson('figma-tokens/Semantic/typeScale.json'),
    space: readJson('figma-tokens/Semantic/space.json'),
    border: readJson('figma-tokens/Semantic/border.json'),
    fontWeight: readJson('figma-tokens/Semantic/fontWeight.json'),
    lineHeight: readJson('figma-tokens/Semantic/lineHeight.json'),
    iconSize: readJson('figma-tokens/Semantic/iconSize.json'),
    motion: readJson('figma-tokens/Semantic/motion.json'),
  },
};

const output = `// Auto-generated by scripts/generateTokenData.js — do not edit directly.\nexport const tokenData = ${JSON.stringify(data, null, 2)};\n`;

const outPath = resolve(root, 'src/stories/helpers/tokenData.js');
writeFileSync(outPath, output, 'utf8');
console.log('Token data written to src/stories/helpers/tokenData.js');
